app = "taqsim-ai"
primary_region = "sjc"  # San Francisco region, change if needed

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512  

[mounts]
  source = "taqsim_data"
  destination = "/app/data"
  size_gb = 1
